# Generated by Django 6.0 on 2025-12-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profissao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('contato', models.CharField(choices=[('TELEFONE', 'TELEFONE'), ('EMAIL', 'EMAIL')])),
            ],
        ),
    ]
