# Generated by Django 6.0 on 2025-12-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profissional_contato_consulta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profissional",
            old_name="name",
            new_name="nome",
        ),
    ]
