# Generated by Django 6.0 on 2025-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_name_profissional_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
